### ISSUE TITLE
Remove jquery

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/webui#133]
We should drop jquery as a dependency and replace all instances with alternatives. For all things bootstrap we should use react-bootstrap and drop bootstrap with jquery

- [x] `scripts/pages/files.js:5:16`
- [x] `scripts/pages/objects.js:3:16`
- [x] `scripts/views/config.js:3:16`
- [x] `scripts/views/editable.js:2:16`
- [x] `scripts/views/filelist.js:2:16`
- [x] `scripts/views/page.js:5:16`

**Comment by diasdavid** [comment]
@travisperson made this on https://github.com/ipfs/webui/pull/159 🎉

**Comment by Dignifiedquire** [comment]
Please do not close until it's merged :)

**Comment by luigiplr** [comment]
Doing in: #195

**Comment by Dignifiedquire** [comment]
Fixed in #159

**Comment by RichardLitt** [comment]
Thanks!
