### ISSUE TITLE
Consistent ES2015 code style

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/webui#138]
* [x] Use arrow functions where possible
* [x] Convert react components to use `class` based syntax when they have `state` otherwise convert them to stateless functional components (https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html)
* [x] No more `var`. The default should be `const` and where mutability is needed use `let` (Enforced through `no-var` in eslint
* [x] Use template strings instead of string concatenation

**Comment by luigiplr** [comment]
Doing in: #195
