### ISSUE TITLE
Convert all bootstrap components to use react-bootstrap

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/webui#140]
There is a lot of use of things like `<div class="some-bootstrap-class"></div>`. All these should be removed in favor of using [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) components.

**Comment by RichardLitt** [comment]
Should this be off of master or webpack?

**Comment by RichardLitt** [comment]
@Dignifiedquire What do you think of https://github.com/RichardLitt/webui/commit/476b427549cde7d0a3ac17f91e5eab3e454014fd. I think that is what you were going for. Let me know, and I'll push it on top of the `webpack` branch.

**Comment by Dignifiedquire** [comment]
@RichardLitt yes that looks good, I did some more changes last night while traveling, so please rebase onto the latest `webpack` branch, and make it a PR against that branch so we have a nice way of tracking these individual changes :)

**Comment by RichardLitt** [comment]
Should be closed now.
