### ISSUE TITLE
Remove unused bootstrap styles

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/webui#153]
Now that we require bootstrap things explicitly we should review all the parts that we use, and remove those not used in https://github.com/ipfs/webui/blob/master/app/styles/bootstrap.less

**Comment by chrisgervang** [comment]
@dignifiedquire is there still work to be done here? #152 looks to have addressed it.

**Comment by dignifiedquire** [comment]
Yes this can be closed, thanks.
