### ISSUE TITLE
WebUI unpopulated

### ISSUE THREAD

**Issue by NightRa** [ipfs/webui#157]
After starting the IPFS daemon, the WebUI came up on localhost:5001 as usual, but with all the fields and all the pages unpopulated - as if it was disconnected from the local IPFS node.
Restarting the IPFS node fixed this.

**Comment by travisperson** [comment]
What version of IPFS are you running?

**Comment by NightRa** [comment]
Latest ver. on dev0.4.0

**Comment by travisperson** [comment]
Have you set any custom http API headers via `ipfs config`?

**Comment by NightRa** [comment]
No, just installed and tried opening it.
```
{
  "HTTPHeaders": null
}
```

**Comment by travisperson** [comment]
Hmm interesting. I'm not sure what was happening then. If you run across this issue again, try opening your developer console and checking the console and network tab to see if there are any errors (best to just copy and paste them all). If I had to take a guess there was probably some 403 error, not sure why restarting the daemon would help unless a config value was changed at runtime.

**Comment by RunningDroid** [comment]
I think I have this with ipfs 0.3.11 but I haven't tried restarting the node yet.

[console log + ipfs config][1]

[1]: https://gist.github.com/RunningDroid/0fcbeb8fe9bc7b6ce29a

**Comment by iav** [comment]
See the same effect with a fresh installed ipfs on Raspberry Pi and web gui runned as web broser addons - firefox and chrome, same effect.
ipfs version 0.3.11
'''
pi@pi:~ $ ipfs config API
{
  "HTTPHeaders": null
}
'''


pi@pi:~ $ ipfs diag sys
{"diskinfo":{"free_space":2.7059597312e+10,"fstype":"ext2/ext3","total_space":3.14599424e+10,"used_space":4.400345088e+09},"environment":{"GOPATH":"","IPFS_PATH":""},"ipfs_commit":"","ipfs_version":"0.3.11","memory":{"swap":{"free":1.04853504e+08,"sin":0,"sout":0,"total":1.04853504e+08,"used":0,"used_percent":0},"virt":{"active":4.76483584e+08,"available":6.43325952e+08,"buffers":5.8843136e+07,"cached":2.49085952e+08,"free":3.58916096e+08,"inactive":8.8702976e+07,"shared":0,"total":9.70764288e+08,"used":6.11848192e+08,"used_percent":33.72995278540778,"wired":0}},"net":{"interface_addresses":["/ip4/127.0.0.1","/ip4/192.168.1.11","/ip6/::1","/ip6/2002:54f5:c121:1:cdda:d18b:4166:ab2b","/ip6/fe80::5eef:c315:6c9d:9ddd"]},"runtime":{"arch":"arm","compiler":"gc","gomaxprocs":3,"numcpu":4,"numgoroutines":770,"os":"linux","version":"go1.5.3"}}
```

**Comment by facastagnini** [comment]
I am having the same problem that @iav described, with ipfs also running in a raspberry pi.

**Comment by facastagnini** [comment]
Ok, I make my webui work as expected, in the end it was a configuration problem.
@iav please try to configure something like this:

'''
"API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Credentials": [
        "true"
      ],
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
         "http://$HOSTNAME:5001",
         "http://$FQDN:5001",
         "http://$RASPBERRYPI_IP:5001",
         "http://localhost",
         "http://127.0.0.1"
      ]
    }
  },
'''

Please replace the upper case variables with the proper value

**Comment by diasdavid** [comment]
You need to configure access if you are accessing from another machine as it is only whitelisted for localhost. 

@NightRa I hope the solutions provided were helpful, let us know if you are still running against this. Closing the issue for now.

**Comment by djh82uk** [comment]
I am also having this issue, and have tried setting the API settings as above aswell as setting the port to listen on further up in the config.  page displays but is blank of all info

**Comment by bjuhn** [comment]
FYI, with localhost the page hits a js error in Safari and fails to load.  It works in Chrome for me.
TypeError: Attempted to assign to readonly property.

**Comment by tfauzia** [comment]
hai ! i want asking something, every time i access this link http://localhost:5001/webui on ubuntu nothing appears on web or sometimes failed, is there a special flow for Ubuntu? Is it the same as access in Windows? FYI i already run daemon on ubuntu when i access that link. 
thank you !
