### ISSUE TITLE
Files added stay in browser localStorage even when unpinned

### ISSUE THREAD

**Issue by slothbag** [ipfs/webui#17]
When adding files using the webui, the browser adds this information into localStorage.

If you then go and ipfs pin rm the content from the command line the file remains in the webui and cannot be removed.

**Comment by jbenet** [comment]
local storage is deprecated and needs to be removed. the file listing should come from the node itself, perhaps using the approach @whyrusleeping used in https://gist.github.com/whyrusleeping/9f2c83f3feed340e21ac

**Comment by jbenet** [comment]
closing in favor of #32
