### ISSUE TITLE
If request to freegeoip.net fails, no peers shown

### ISSUE THREAD

**Issue by slothbag** [ipfs/webui#18]
https://github.com/protocol/ipfs-webui/blob/c0c42c092ba2e34a7a0818e45dc79d92544466f4/js/getlocation.js#L15

If this request fails, the peer list is not shown.  My node does not have internet access but is still connected to IPFS.

**Comment by jbenet** [comment]
Ah yes, this is a problem. It also comes up when adblock extensions block access to freegeoip

**Comment by CaioAlonso** [comment]
I'm also getting this in Firefox's console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://freegeoip.net/json/<ip address>. This can be fixed by moving the resource to the same domain or enabling CORS.
```

**Comment by jbenet** [comment]
interesting-- is anyone else also getting this CORS problem? 

we can't set CORS on freegeoip, but we may be able to switch to something else

**Comment by CaioAlonso** [comment]
In Chromium I get:
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```
for every freegeoip request. I guess it is the same CORS problem.

I did a little bit of research, and if our API server sent the `Access-Control-Allow-Origin: *` header, wouldn't it solve the problem?

**Comment by jbenet** [comment]
We don't control the geoip server. Not clear why t works on some users and not others. What's your browser?



—

**Comment by CaioAlonso** [comment]
@jbenet, running on a clean Firefox install gives me no errors. It is probably some privacy extension I'm using. Sorry about that.

**Comment by jbenet** [comment]
We should still work with them. Wonder how big the DB is and how stable ip prefixes are. We could make one massive ipfs crdt of all the allocations and just use that.



—

**Comment by aubergene** [comment]
[Freegeoip](https://github.com/fiorix/freegeoip) is another Go project, so you could run your own server. The database they use is from [MaxMind](http://dev.maxmind.com/geoip/geoip2/geolite2/) and it updates quite regularly, for city level it's about 30Mb as CSV.

**Comment by jbenet** [comment]
@aubergene ahh thanks! I think we should store the db in ipfs itself.

**Comment by jbenet** [comment]
Ok, so three approaches:

1. (shortest term) find some fix for this. maybe we can replicate it, or proxy requests, or pop up a warning to the user (maybe on top of the globe) that it's getting blocked by adblock.

2. (short term) I imagine we can even run a resolver on the http api itself... not to add the kitchen sink, but would be nice not to depend on services being live (self containment)

3. put a geoip database on ipfs itself!! this would be very cool, but will take a bunch of time to get right. it's a medium sized project.

**Comment by jbenet** [comment]
I think we should do (1) and/or (2)

**Comment by krl** [comment]
#44 should solve this as well
