### ISSUE TITLE
/files with thousands of files added makes my browser hang

### ISSUE THREAD

**Issue by CaioAlonso** [ipfs/webui#20]
I don't know how many files/directories I have added, but as an experiment I have added thousands of them.

Browsing to `http://localhost:5001/ipfs/QmXX7YRpU7nNBKfw75VG7Y1c3GwpSAGHRev67XVPgZFv9R/#/files/all` makes Firefox and Chromium on Linux hang a lot.

**Comment by whyrusleeping** [comment]
would be nice to have a sort of 'range query' on the files so we can just show 10-20ish at a time. I remember @travisperson was working on a cool 'infinite scrolling' thing in react that did some nifty loading stuff to solve this very problem (if i remember correctly)

**Comment by jbenet** [comment]
Yeah, we need to support range queries on the ipfs api

**Comment by travisperson** [comment]
Ya!

https://github.com/seatgeek/react-infinite

There was an issue with it not being able to be included via npm which was just recently fixed. Loading the files from IPFS shouldn't be an issue, though providing range queries would be great.

**Comment by jbenet** [comment]
That sgtm. 



—

**Comment by jbenet** [comment]
this bug is very annoying to have :(
