### ISSUE TITLE
The package cheerio@0.20.0 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by suisha** [ipfs/webui#245]
I'd like to contribute but I'm having trouble installing the app. Does `webui` have a preferred node/npm version? I followed the "Installation and running" instructions and ran into `npm install` errors using node 4.2.2 and npm 2.14.16. OS is OSX 10.9.5.

> [fsevents] Success: "/Users/dmai/node-play/github.com/suisha/webui/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
> npm ERR! Darwin 13.4.0
> npm ERR! argv "/Users/dmai/.nvm/versions/node/v4.2.2/bin/node" "/Users/dmai/.nvm/versions/node/v4.2.2/bin/npm" "install"
> npm ERR! node v4.2.2
> npm ERR! npm  v2.14.7
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package cheerio@0.20.0 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer chai-enzyme@0.2.2 wants cheerio@^0.19.0
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/dmai/node-play/github.com/suisha/webui/npm-debug.log

**Comment by dignifiedquire** [comment]
The best way is to upgrade to `npm@3` to solve the issue.

**Comment by suisha** [comment]
Thanks, I managed to get everything up and running.

Would you mind if I added the npm version to `README`? Also, do you have any thoughts on adding a `.nvmrc` to the project so people know what the right version of node is?

**Comment by dignifiedquire** [comment]
Glad to hear, the node version is documented in here: https://github.com/ipfs/webui/blob/master/package.json#L98 but I'd be happy to see a PR adding the node and npm versions to the readme.
