### ISSUE TITLE
Files added via the webui can not be unpinned via the webui.

### ISSUE THREAD

**Issue by travisperson** [ipfs/webui#31]
Current when adding anything file to the webui they get pinned recursively. Any file you add via `ipfs add` gets pin recursively to protect the file, and all it's blocks, from a `gc`. The `node-ipfs-api` currently does not send a `-r`/`--recursive` when running the `pin rm` command (`api.pin.remove`), so on any file you try to "delete" (the X), will return an error saying it is added recursively.

**Comment by whyrusleeping** [comment]
We should use -r to unpin there. IMO, all 'unpin' and 'pin' operations should be recursive by default.

**Comment by travisperson** [comment]
This actually may be a duplicate of #21, taking a closer look at that issue it appears it's referring to unpinning not work?

**Comment by jbenet** [comment]
No I think this is that files added in webui get tracked in local storage. We shouldn't do that anymore



—

**Comment by travisperson** [comment]
Alright cool, this issue can be fixed with https://github.com/mappum/node-ipfs-api/issues/5

**Comment by jbenet** [comment]
@travisperson update on this?

**Comment by travisperson** [comment]
I can get this done tomorrow night, should be a super fast fix now that we have updated the node ipfs-api module.
