### ISSUE TITLE
Remove local storage

### ISSUE THREAD

**Issue by jbenet** [ipfs/webui#32]
today, when files are added via webui they get put on local storage. 

this should no longer be the case. we should not be using browser local storage for this, as it gets inconsistent with the ipfs repo itself. all[1] state should go through the api. 

[1] i think all. post if you think any should remain in local storage. possible that some user preferences -- now i think about it i think @STRML made it a preference to pick a particular globe. (sorry i haven't published that, was waiting on some bugfixes)

**Comment by STRML** [comment]
Agreed, only webui-specific prefs should be in localStorage (so they don't have to clutter up the API).

Webui-specific preferences include things like themes, open tabs, whatever we might add. There shouldn't be much of it. Application state should be in the URL bar if possible.

**Comment by slothbag** [comment]
I'm just guessing here, but maybe the reason the data is being stored in localStorage is because its storing things like the original file name, mime type and size.. although I guess original filename is probably the only useful thing there.  If i'm not mistaken ipfs does not store the original filename so there would be no way to retrieve it via the API

**Comment by jbenet** [comment]
Yeah we should catch those. We could store that information as dir and metadata objects in ipfs.



—

**Comment by krl** [comment]
starting on this now, i cannot assign myself for some reason though?

**Comment by krl** [comment]
Ok, i guess the problem here is how do we actually list files added by the webui, without keeping local storage? We cannot list everything of course.

One way would be putting it in /ipns/local/webui-added or something

I guess the idea is not to take out the files list completely.

**Comment by krl** [comment]
the problem with this approach is that everything will be made public to people who know your ipns name

**Comment by krl** [comment]
I'm going for this though, no file is private at this point anyway. But maybe we should add a warning as well.

**Comment by krl** [comment]
suspending this until further notice, the problem is that there does not seem to be a way through the api to add files to ipns paths.

**Comment by jbenet** [comment]
> i cannot assign myself for some reason though?

have added you to the org. (only rules are: 
- dont push to master, 
- don't rebase other people's branches, 
- dont merge without CR/LGTM)

> how do we actually list files added by the webui, without keeping local storage? We cannot list everything of course.

for now we list things with 

```
> ipfs refs local
> ipfs pin ls --type=all
```
this of course isn't a good way, so there's some issue about adding a way to find roots. @whyrusleeping had a way to do it somewhere that we could add to go-ipfs directly. 

> One way would be putting it in /ipns/local/webui-added or something
> the problem with this approach is that everything will be made public to people who know your ipns name

i'd rather not do this approach because people will be publishing ipns names to other things. 

>  there does not seem to be a way through the api to add files to ipns paths.

you can-- think of it like git:

- first, add all the object as ipfs files.
- resolve the ipns name to an ipfs object 
- mutate the object and store it again.
- publish the ipns name to point to new object (in git this is writing the branch name to point to the new object)

but i agree this is very cumbersome through the api. two ways out:

1. make this a function in js side
2. make it a command in ipfs side (we want to do this anyway-- there's the idea of having an `ipfs mv` command type of thing. this hasn't been specced out well).

---

---

for the immediate use case though, it may be that listing the recursive pins only: `ipfs pin ls --type=recursive` is a good proxy. the roots wont have names, sadly :(.

--- 

one possible way out of this, is that instead of finding roots, we could have an ipfs node keep a master root object of all the files it added locally. that way, when we 

```
> ipfs add -r <path>
<hash>
```

we could add a link:

```
<hash of current node repo state>/local-files/`basename <path>` -> <hash>
```

i've been meaning to move a lot of the internal node's repo management to ipfs objects themselves (like pins could be ipfs objects listed under:

```
<hash of current node repo state>/id
<hash of current node repo state>/keys
<hash of current node repo state>/pins/recursive/...
```

i think this is a very good approach because it makes the entire node's internal state be ipfs objects itself (and replicatable etc). which means we can have a single hash that represents the node's state (and we move entirely off of leveldb)

cc @whyrusleeping for thoughts

**Comment by krl** [comment]
yes, having node state as an object sounds very nice. Maybe even use ipns with the node-id to keep track of this.


In other news, i've managed to get a list of recursivly pinned files using --recursive, and piping the results to ipfs ls, singling out the nodes with named links and displaying them.

The only thing that's left is adding a wrapper directory around the file from the webui, which seems to need some api extensions as well. Still researching this.

**Comment by jbenet** [comment]
> yes, having node state as an object sounds very nice. Maybe even use ipns with the node-id to keep track of this.

yeah, more and more this sounds like TRTTD. and use `ipfs name publish` ... to publish either other keys, or names within `$REPO_HASH/names/<name>`.

> In other news, i've managed to get a list of recursivly pinned files using --recursive, and piping the results to ipfs ls, singling out the nodes with named links and displaying them.

excellent!

**Comment by travisperson** [comment]
@krl directory support is one of my near future goals for the `node-ipfs-api` see https://github.com/ipfs/node-ipfs-api/issues/4.

**Comment by Dignifiedquire** [comment]
Reviving this thread, I was thinking maybe it makes sense to combine the component responsible for directory listings [dir-index-html](https://github.com/ipfs/dir-index-html) together with the file list here. It would have two "modes" one where it's in a read only state (the normal listing) and one where you can edit things like in the webui + some more nice stuff similar to the UI dropbox for example provides. 

Thoughts? Good | Bad | Crazy?

**Comment by jbenet** [comment]
- this issue was originally about using "local storage" to record which files are added. this is still a problem that needs to be removed. we need to just check the local repo (maybe using an ls-roots style command, there's one floating in a PR for go-ipfs, not yet merged).
- and i think "directory support" (adding directories) already works through the ipfs-node-api, though not yet through the drag and drop.
- aside from that, the UI changes @Dignifiedquire mentions sound good in terms of being able to edit things. 
- i would  really like a "pin / unpin" button, for one.
