### ISSUE TITLE
Coordination

### ISSUE THREAD

**Issue by jbenet** [ipfs/webui#33]
Hey everyone watching, we want to push to a 0.2.0 release of the webui next week. It will mostly be bug fixes and a couple improvements.

If you want to help with this, please self-assign an issue (if you don't have collab access to repo, can ask for it or just leave a comment at the end). -- but please keep assignments "fresh" (i.e. dont keep something assigned to self while not actively working on it).

Rough plan:
- `0.2.0` - bugfixes and so on
- ipfsdctl + atom-shell packaged app
- `0.3.0` - continue with new features and enhancements

cc @krl @travisperson @STRML

**Comment by travisperson** [comment]
Just saw this announcement

http://blog.atom.io/2015/04/23/electron.html

**Comment by jbenet** [comment]
Yep! 



—

**Comment by Dignifiedquire** [comment]
@jbenet can we close this?

**Comment by jbenet** [comment]
Yep!
