### ISSUE TITLE
Can not commit anything

### ISSUE THREAD

**Issue by travisperson** [ipfs/webui#34]
I'm running into all sorts of crazy errors when trying to commit anything. I just made a branch off master and I can't commit anything due to the post-commit hooks that are in place.

https://gist.githubusercontent.com/travisperson/37a498c6d5b4bc4873b4/raw/gistfile1.txt

/cc @STRML

**Comment by jbenet** [comment]
@travisperson this is my doing-- @STRML wanted to add some linting and I opted to use https://github.com/feross/standard -- i think there's a binary that fixes things.
