### ISSUE TITLE
EC6 incompabilities?

### ISSUE THREAD

**Issue by krl** [ipfs/webui#37]
On running make serve, and checking the files page, i get multiple errors along the line of:

Uncaught TypeError: undefined is not a function files.jsx:21

the offending line is:

```js
pinned.Keys.sort()
```

This seems to be a EC6 feature, but it's not being transpiled in the build.

As a workaround i replaced the places where this was used with lodash.

@travisperson 
Is there some special setup to have it transpile in the dev-env?

**Comment by travisperson** [comment]
Are you developing against the latest master?

This is an issue in the API change moving from returning an array of keys to an object of key value pairs. ES6 might be able to sort on keys, but I don't think this is an issue with that.

See: https://github.com/ipfs/webui/pull/35

**Comment by Dignifiedquire** [comment]
Not seeing this anymore. Please reopen if it still happens
