### ISSUE TITLE
The "delete" button in the web-interface for local data has no effect

### ISSUE THREAD

**Issue by Kuurusch** [ipfs/webui#512]
In the web-interface under "files" there you can see a list of the local files. If I click under "action" onto the "delete" button (x), it has no effect, say the file stais.

Thanks for fixing this!

Version of ipfs: 0.4.2 and 0.4.3

**Comment by xrogaan** [comment]
Still affects 0.4.4.

**Comment by Kuurusch** [comment]
I use newest relese of go-ipfs 0.4.6-rc-1 and the delete button still has no effect!
