### ISSUE TITLE
No way to monitor bandwidth usage from webui

### ISSUE THREAD

**Issue by voltagex** [ipfs/webui#541]
(renamed issue, this is both a client and a ui issue)

Two problems:

a) I need to be able to limit bandwidth usage
b) there's no way to see _why_ ipfs is using so much bandwidth

**Comment by diasdavid** [comment]
Hi @voltagex, thanks for reporting. This is indeed a issue with go-ipfs directly. You can track the conversation here https://github.com/ipfs/go-ipfs/issues/3429
