### ISSUE TITLE
QmazRLjjzLYDnxVMEMEmKd5w8KxYMyaQ3wMakLcz5iKyNc says "Object data (59051 bytes)" but is actually a 61347 byte picture

### ISSUE THREAD

**Issue by benrayfield** [ipfs/webui#563]
http://localhost:5001/ipfs/QmU3o9bvfenhTKhxUakbYrLDnZU7HezAVxPM6Ehjw9Xjqy/#/objects/\ipfs\QmazRLjjzLYDn

**Comment by diasdavid** [comment]
@benrayfield that is because you are using the Object API to get the statistics of a _single node_ but the file is multiple nodes :)
