### ISSUE TITLE
4.5-dev from git webgui connection shows zero

### ISSUE THREAD

**Issue by edt-xx** [ipfs/webui#568]
ipfs swarm peers shows over a hundred connections.  None are shown on the webgui.  Worked fine with 4.4.  This is with an up to date arch install on 4.8.6 with chrome and also verified on firefox.

ipfs was built from git ( go-ipfs-git-0.4.5dev.r333.g8d6ac7a-1-x86_64.pkg.tar ) where g8d6ac7a refers to the commit.

What else will help?

Thanks
Ed

**Comment by dignifiedquire** [comment]
Are there any errors in the console/devtools?

**Comment by edt-xx** [comment]
No.  Console looks normal.

**Comment by Kubuxu** [comment]
It is probably because peers API was changed. See https://github.com/ipfs/js-ipfs-api/issues/413

**Comment by Kuurusch** [comment]
Ok, same problem!
Have I to update the webui seperatly or is it enougth to use ipfs-update?

**Comment by dignifiedquire** [comment]
@Kuurusch the webui needs to be fixed in this repo, and then it will be added to the next release of go-ipfs.

**Comment by letozaf** [comment]
Version information: master branch version of 30 January 2017 (Ipfs 0.4.5, release candidate 1 )
Type: BUG
Priority: P3
Description:
The Webui does not display peers, peers always remain 0. In the previous version the peers are shown.

**Comment by Kuurusch** [comment]
I have still the same problem. Updated to version 0.4.6-rc1 and it's still the old version of the web ui. Or at least it looks so. No peers in web ui, but in the console I have plenty.
Any idea, how to debug this situation? Where is actually the webui installed? Could it be, that the install path has changed and it points still to the old version in the old path, or something like that?

I'm working with OSX

**Comment by Spyder3W** [comment]
the problem occurs if you use local ip or external ip or domain
Requests are handled correctly
`http://ipfs.XXXXXX.com:5001/api/v0/swarm/peers?stream-channels=true`

localhost or 127.0.0.1 - work
