### ISSUE TITLE
scrolling on connections page shouldnt move the globe

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/webui#57]
when you have a lot of connections on the connections page, and you scroll down, the globe moves with the page. I think it would look nicer if only the connections list scrolled, knowing nothing about javascript, i'm not sure how easy that would be to do.

**Comment by jbenet** [comment]
I think this was resolved in #58

**Comment by jbenet** [comment]
I think this was resolved in #58

**Comment by dignifiedquire** [comment]
Closing as when #213 is done we don't need this anymore
