### ISSUE TITLE
Create Service with PM2

### ISSUE THREAD

**Issue by genesischain** [ipfs/webui#579]
Is there any info on creating a pm2 service for the webui? I can't workout which app file should be launched with "pm2 start xxxxx.js". assuming it is possible to do.

I know very little about npm/js etc.

Any help much appreciated.

**Comment by aphelionz** [comment]
Hi @genesischain, please see the discussion here: https://github.com/Unitech/pm2/issues/1317. What you want to do is run `npm start` from pm2, not the entry point js file.

About halfway down there is a comment, https://github.com/Unitech/pm2/issues/1317#issuecomment-137133492, that solves the issue you're looking at. Note that you may need to replace `/usr/local/bin/npm` with your system's npm executable path.

A command like `which npm` would tell you that, or you could use /usr/bin/env, something like:

`pm2 start "/usr/bin/env npm" --name "myAPP" -- start

Please post what worked for you to the thread before closing the issue!

**Comment by genesischain** [comment]
Hi @aphelionz 

Thanks for the info, worked a treat. I simply used:  
root@GB3ZZD1BACK02:/ipfs/webui# pm2 start npm -- start

There's a post a few lines down in that discussion you posted.

Cheers
