### ISSUE TITLE
POST requests not allowed by default CORS settings

### ISSUE THREAD

**Issue by underyx** [ipfs/webui#586]
I started up the Docker image, and the WebUI was broken. After a bit of digging, I found that only GET cross-origin requests were set to be allowed in the default config. Running this command fixed my problems:

```
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods '["GET", "POST"]'
```

**Comment by diasdavid** [comment]
Thanks @underyx :) do note that we have a note on the README for that https://github.com/ipfs/webui#config  ;)
