### ISSUE TITLE
WebUI does not work for non local machine

### ISSUE THREAD

**Issue by dsvi** [ipfs/webui#591]
The WebUI, returned by `<IPFS API URL>/webui` has hardcoded `localhost` in it. So it doesn't really work for any other machine than `localhost`
It should take the API address from the go-ipfs config, not just force it to be `localhost`.

**Comment by diasdavid** [comment]
@dsvi that intended and is a security protection mechanism to make sure that you can't have access to admin features outside of your local machine :) Hope this clarifies

**Comment by dsvi** [comment]
Not really, no. More confuses, than clarifies.
So i do have remote access to the json RPC API, through which i get the page and can control the daemon, but through the page itself, i can't control it.
What kind of "security" exactly this provides? 
It really sounds very silly, to put it mildly. The page itself doesn't have anything to do with security. It's a convenient GUI to the already provided access RPC.

**Comment by DevonJames** [comment]
@diasdavid what specific security concerns would there be if the webui wasn't hardcoded to work with localhost only?

**Comment by olizilla** [comment]
See: https://github.com/ipfs-shipyard/ipfs-webui/issues/836
