### ISSUE TITLE
All of POST request's results are 403 Forbidden 

### ISSUE THREAD

**Issue by shanelau** [ipfs/webui#596]
error: 

![image](https://user-images.githubusercontent.com/3140898/28062224-d4572dca-665f-11e7-8e5d-ab5cf83e3cdb.png)

ipfs gateway config:

![image](https://user-images.githubusercontent.com/3140898/28062263-ecd9c556-665f-11e7-98e4-1890ab59ff0d.png)

**Comment by shanelau** [comment]
config ~/.ipfs/config

```
  "API": {
    "HTTPHeaders": {
      "Access-Control-Allow-Methods": [
        "PUT",
        "GET",
        "POST"
      ],
      "Access-Control-Allow-Origin": [
        "*"
      ]
    }
  },
```

**Comment by vutuyetmai130398** [comment]
@shanelau I try to fix the ~/.ipfs/config as the same you, but it still go into the Web UI of IPFS when i run http://local:5001/ipfs/(PeerId)/#. It show me the 403 error.

**Comment by hleb-albau** [comment]
Same problem ;(

**Comment by NatoBoram** [comment]
I tried to copy @shanelau's snippet but it seems like this might be a bug with `go-ipfs` v0.5.0-rc1.

**Comment by aliawais0007** [comment]
This Command Works for me 
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin '["'"$origin"'", "http://127.0.0.1:8080","http://localhost:3000"]' you can allow the request from multiple origins
