### ISSUE TITLE
Missing vendored files

### ISSUE THREAD

**Issue by travisperson** [ipfs/webui#6]
`/static/bootstrap/3.3.2/css/bootstrap.min.css` [This link should resolve in this repo](https://github.com/protocol/ipfs-webui/tree/master/static/bootstrap/3.3.2/css/bootstrap.min.css)

https://github.com/protocol/ipfs-webui/blob/master/html/index.html#L17

`/static/bootstrap/3.3.2/js/bootstrap.min.js` [This link should resolve in this repo](https://github.com/protocol/ipfs-webui/tree/master/static/bootstrap/3.3.2/js/bootstrap.min.js)

https://github.com/protocol/ipfs-webui/blob/master/html/index.html#L28

These either need to be vendored or produced during the static step in gulp.

**Comment by STRML** [comment]
This can probably be closed?

**Comment by jbenet** [comment]
yep!
