### ISSUE TITLE
Path Resolve error for "fontawesome-webfont.woff2" on fresh IPFS install

### ISSUE THREAD

**Issue by zigguratt** [ipfs/webui#60]
I installed IPFS on both Debian Sid and Centos 6.6 (Final). When running the daemon I get:

    ERROR core/serve: Path Resolve error: no link named "fontawesome-webfont.woff2" under QmWjympWW8hpP5Jgfu66ZrqTMykUBjGbFQF2XgfChau5NZ gateway_handler.go:436

It doesn't seem to affect functionality, but something is definitely amiss.

go version go1.4.2 linux/amd64
ipfs version 0.3.4

**Comment by travisperson** [comment]
Looks like we should have a step in the build process that moves fonts into the correct directory so we can keep up to date with font-awesome.

**Comment by jbenet** [comment]
@d6e just ran into this problem. we should fix this

**Comment by Dignifiedquire** [comment]
Should be fixed in the latest version. But that one is not deployed @jbenet can you let me know how that happens?

**Comment by jbenet** [comment]
i deployed one recently-- in the last 2-3 weeks.

**Comment by Dignifiedquire** [comment]
@jbenet okay thanks, are you still seeing this issue?

**Comment by Dignifiedquire** [comment]
Should be fixed in master
