### ISSUE TITLE
webui, url localhost:5001/webui wrong

### ISSUE THREAD

**Issue by flowpoint** [ipfs/webui#601]
when accessing webui via, "localhost:5001/webui", i land at the url but with port 8080.
so: http://127.0.0.1:8080/ipfs/hash/#/ 
instead of http://127.0.0.1:5001/ipfs/hash/#/
using go-ipfs 0.4.11 as systemservice with the ipfs companion extension 2.0.12

**Comment by Kubuxu** [comment]
It is the ipfs-companion redirecting look a-like ipfs hashes. Can you report it to https://github.com/ipfs/ipfs-companion .

**Comment by flowpoint** [comment]
[https://github.com/ipfs/ipfs-companion/issues/291](url)
