### ISSUE TITLE
Files page remove pin button broken

### ISSUE THREAD

**Issue by sickill** [ipfs/webui#607]
__Version information:__

go-ipfs version: 0.4.13
Browser: Firefox, Chrome (reproducible on all)

__Type: Bug__

__Severity: Low__

__Description:__

The X remove buttons on the Files page of the web ui are broken. If you click any of them, then the web UI goes to the front page (because the remove button is a link to "#" and the preventDefault() method is never called on the click event object), and this error appears in the console: "TypeError: t.preventDefault is not a function"

(I just copied it from https://github.com/ipfs/go-ipfs/issues/4269 and updated go-ipfs version to the one I use)

**Comment by hacdias** [comment]
Hello @sickill! Thanks for reporting this! 😄 Fortunately, I can tell you that the latest version of WebUI (the one in this repository) doesn't contain this issue anymore. I think this should be closed. /cc @diasdavid

**Comment by diasdavid** [comment]
@whyrusleeping @lgierth @Kubuxu can we ship the new (fixed) webui with the next release of go-ipfs?

**Comment by lgierth** [comment]
Sure! Pin it, then update [core/corehttp/webui.go](https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go)

**Comment by diasdavid** [comment]
@hacdias wanna do the honors? @lgierth can @hacdias have pinbot perms?

**Comment by lgierth** [comment]
@diasdavid `!befriend <nick> pin`

**Comment by diasdavid** [comment]
@lgierth I tried but it didn't work:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1211152/33474076-e62878b6-d670-11e7-9cf5-ed1114ebe3ea.png">

**Comment by diasdavid** [comment]
@hacdias you are now a pinbot friend. Wanna update go-ipfs hash?

Also, wanna add this route to js-ipfs daemon?

**Comment by hacdias** [comment]
@diasdavid 

> @hacdias you are now a pinbot friend. Wanna update go-ipfs hash?

Sure, but how? I know I have to pin an hash with a name. The name is `go-ipfs`, right? But what will be the hash in this case?

> Also, wanna add this route to js-ipfs daemon?

Yes, but where? I'm not yet familiarized with everything 😛

**Comment by diasdavid** [comment]
### For go-ipfs

@hacdias on the root of this repo do `npm run build` (see https://github.com/ipfs/webui#building) that will create a folder. Then do `ipfs add -r dist` and make sure your daemon is on.

With your daemon on go to pinbot and do `!pin <the hash you got from ipfs add -r> webui`

Once that is finished, you can now submit a PR to https://github.com/ipfs/go-ipfs/blob/master/core/corehttp/webui.go

### For js-ipfs

Add a route here for `/webui` https://github.com/ipfs/js-ipfs/blob/master/src/http/gateway/routes/gateway.js

**Comment by hacdias** [comment]
> For go-ipfs

Done!

> For js-ipfs

I'll see that later hopefully 😄

**Comment by hacdias** [comment]
@diasdavid, adding a route for `/webui` on gateway.js won't work since `/webui` tries to connect to the API in that same domain in that same port. It tries to connect to the API on `127.0.0.1:9090` instead of `127.0.0.1:5002`. 

The same happens with go-ipfs, but go-ipfs has `/webui` also available on `:5001` so it works.

**Comment by diasdavid** [comment]
@hacdias you got it right. You should indeed create that endpoint on the API which is on the folder next to the gateway -> https://github.com/ipfs/js-ipfs/tree/master/src/http/api

**Comment by hacdias** [comment]
@diasdavid done: https://github.com/ipfs/js-ipfs/pull/1124 🎈

**Comment by diasdavid** [comment]
Thank you @hacdias ! :D Closing this issue then :)
