### ISSUE TITLE
Globe broken in responsive layout

### ISSUE THREAD

**Issue by krl** [ipfs/webui#62]
#58 broke the small-screen view, as the peer-list completely obscures the globe.

@travisperson i agree that a fixed globe is better, could we find a way of doing it more screen-size responsive?

**Comment by travisperson** [comment]
Darn, wasn't as easy of a thing as I hoped. There are a few options but not sure if we really want to pursue any of them. For now we probably should just revert the change.

**Comment by jbenet** [comment]
@travisperson yeah, it was too much code.

**Comment by jbenet** [comment]
@travisperson it's not published so if we fix it soon, it's fine. if not soon, can you PR a revert?

**Comment by travisperson** [comment]
I'll probably open a PR to revert. My current idea to do this (as it appears we can't do it with css) would be to use the scroll distance and update the position and using Javascript. However, we don't want to do this when we move down to mobile, so not super simple fix.

I'll take a look at it later as it's not the big of a deal and I'd rather work on node-ipfs and other projects right now.

**Comment by jbenet** [comment]
> I'll probably open a PR to revert. My current idea to do this (as it appears we can't do it with css) would be to use the scroll distance and update the position and using Javascript. However, we don't want to do this when we move down to mobile, so not super simple fix.

oh no. that's annoying. why cant this be done with css? we can adjust the size of the globe using media queries or relative % sizes.

**Comment by jbenet** [comment]
ok sounds good, let's revert
