### ISSUE TITLE
Use links in the connections list?

### ISSUE THREAD

**Issue by ThomasWaldmann** [ipfs/webui#69]
I wondered what the connections list is good for (except of "yay, I have 50 peers and they are all on earth!").

It shows me the node id of my peers, but it doesn't link the nodeid to the gateway URL for /ipns/<nodeid>, which would be a nice way to learn about their published content.

**Comment by travisperson** [comment]
:+1:

**Comment by travisperson** [comment]
So this has some issues that we won't be solve to resolve for a while. There is no good way to know what host to use to link to the `/ipns/<hash>`. And we have to have this host to do this as the `/ipns` namespace is complete blocked via port 5001.

Until we have an easy way to resolve the correct hostname for use adding any external links like this will cause issues for certain setups, such as using a reverse proxy.

**Comment by Dignifiedquire** [comment]
Closing for now
