### ISSUE TITLE
New build system

### ISSUE THREAD

**Issue by giodamelio** [ipfs/webui#87]
The webui is about to get an overhaul, and the build system needs to be figured out before too much work is done.

Here are some goals

 - [ ] Modularize everything. See #73 
 - [ ] Create test suit. See #38 
 - [ ] Build ES2015 with Babel

The two main options are Webpack and Browserify.

## Browserify:

**Pros:**

 - Simple, follows Unix philosophy
 - Mature and fast

**Cons:**

 - Integrating non-JS assets requires writing non portable shell scripts

## Webpack:

**Pros:**

 - Fully featured. Plugins allow for awesome things like react hot-reloading
 - Loads most any type of file. All assets can be processed with one tool

**Cons:**

 - A bit of magic. Complicated config(well documented though)

**Comment by Dignifiedquire** [comment]
Another pro for webpack: Excellent hot-reloading support

**Comment by Dignifiedquire** [comment]
Also a point to think about: finding a common setup for different UI parts so that we don't have to rediscuss this on every project. Electron-app is currently getting a webpack setup with hot reloading and assets bundeling in https://github.com/ipfs/electron-app/pull/43 which I feel would very well work for this project as well.

**Comment by giodamelio** [comment]
I am thinking along the same lines. We could create a repo of IPFS related react components, that could be shared between the electron app, webui and any other future JS projects.

Another option is web components. [Browser support is decent](http://caniuse.com/#search=components), and I believe there are polyfills. I don't know if the tooling is there yet though.

**Comment by jbenet** [comment]
Take a look at the webcomponents work by @krl -- ideally many of these could be webcomponents living on ipfs itself.



—

**Comment by giodamelio** [comment]
Hmm, that's interesting([Link](https://github.com/ipfs/webui/tree/modularized-webui)). I like the idea of having separate web components hosted on IPFS. The tooling needs some work though. I will have to read up on web components.

**Comment by Dignifiedquire** [comment]
To be honest I'm not a big fan of web components after reading up on them a bit more, also it looks like react + web components is not a really good fit https://github.com/facebook/react/issues/5052 

The stuff from @krl looks interesting but I can't help but wonder, what actual benefit do we get from using web components instead of just creating dist bundles that live on ipfs.

**Comment by giodamelio** [comment]
Web components don't have anything todo with IPFS per-say, it's more the fact they are a standard instead of a library. They are supported natively.

**Comment by Dignifiedquire** [comment]
Not sure I would say this is real native support: http://caniuse.com/#search=web%20components

**Comment by giodamelio** [comment]
Ya, support is not too good yet. I think there are some polyfills, but it doesn't seem ready yet.

**Comment by jbenet** [comment]
WebComponents is a very important internet standard, and we've been talking to a lot of people about them. One exiting thing is making a big push to make WebComponents that live on IPFS and need no origin server at all, that anybody can use, like true "npm modules for frontend". These can often be small enough that we can offer to pin them for people.

WebComponents is the result of pushes towards creating true modular, reusable pieces for UIs. they have significant traction already, and we stand a chance to improve the ecosystem dramatically by coming up with good ways to {find, serve, archive} these. 

Another thing i'm very excited about is being able to make an app from scratch and use WebComponents for the hard stuff, _directly from the web._ never touch a locla server. only browser, a known ipfs gateway (with write access), and some WebComponents in the network.

**Comment by giodamelio** [comment]
I am going to try to build a simple web component (unrelated to webui), and maybe come up with something that could be used as a template for making IPFS hosted web components.

**Comment by Dignifiedquire** [comment]
@giodamelio going to start work on a build system that integrates webpack with ipfs as best as possible soon. Let me know if you are still interested in helping out

**Comment by giodamelio** [comment]
@Dignifiedquire Yes, I do want to help out. Is there going to be a new branch that I can track?

**Comment by Dignifiedquire** [comment]
@giodamelio there will be, I'm still researching some things but will add a reference here as soon as I have some code

**Comment by giodamelio** [comment]
Thanks

**Comment by RichardLitt** [comment]
@Dignifiedquire Where are we at the moment?

**Comment by Dignifiedquire** [comment]
@RichardLitt somewhere in the middle ;) My pr does webpack + es2015 + base test setup, so we are only missing modularization which I want to delay until we have the code in a better state

**Comment by RichardLitt** [comment]
Ok, cool. So, the next step for people wishing to close _this issue_ are: check out other issues, and see if there is anything you can do for them?

**Comment by Dignifiedquire** [comment]
@RichardLitt I think I will close this issue as soon as #130 is merged and create more modular issues around all the things needed to be done.

**Comment by RichardLitt** [comment]
Sounds good.

**Comment by RichardLitt** [comment]
Whoop!
