### ISSUE TITLE
DAG links are broken

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/webui#89]
Pasting the hash of a local file in the search bar at the top or clicking the `DAG` link in the files list always results in a 404 page for me. 

```
ipfs version 0.3.7 (latest version through homebrew)
```

**Comment by jbenet** [comment]
@Dignifiedquire is this still a problem in the new webui? (achin is seeing the same)

**Comment by Dignifiedquire** [comment]
Sometimes they are broken :(

**Comment by Dignifiedquire** [comment]
Fixed in the latest version
